### ISSUE TITLE
Petite faute de frappe

### ISSUE THREAD

**Issue by UnDesSix** [rchallie/netwhat#4]
Je peux me tromper, mais il me semble qu'il y a une petite faute de frappe concernant le premier exemple de la partie "Masque de sous réseau".

1 ET 1 = 1 (et non pas 0)

Super travail les gens en tout cas ;)

**Comment by rchallie** [comment]
@UnDesSix Merci beaucoup d'avoir remarqué et remonté ça ! J'ai fait la modification.
Merci d'apprécier notre travail !
